---
variables:
  LEKTOR_BUILD_FLAGS: scss generate-cw-fractions
  SITE_URL: community.torproject.org
  STAGING_URL: community.staging.torproject.net
  TRANSLATION_BRANCH: communitytpo-contentspot

include:
  - project: tpo/tpa/ci-templates
    file:
      - lektor.yml
      - static-shim-deploy.yml

# retrieve latest tpo/community/{onion-services/ecosystem,policies} build
# artifacts and place files under public/{onion-services/ecosystem,policies}
# such that they are deployed to community.tpo/{onion-services/ecosystem,policies}
.lektor:
  scripts:
    post-build:
      # policies
      - mkdir public/policies
      - wget -q https://gitlab.torproject.org/api/v4/projects/1972/jobs/artifacts/main/download\?job\=build -O policies.zip
      - unzip policies.zip -d public/policies
      - mv public/policies/public/* public/policies
      - rmdir public/policies/public

      # ecosystem
      - mkdir public/onion-services/ecosystem
      - wget -q https://gitlab.torproject.org/api/v4/projects/2439/jobs/artifacts/main/download\?job\=build -O ecosystem.zip
      - unzip ecosystem.zip -d public/onion-services/ecosystem
      - mv public/onion-services/ecosystem/public/* public/onion-services/ecosystem
      - rmdir public/onion-services/ecosystem/public
