---
variables:
  LEKTOR_BUILD_FLAGS: scss
  SITE_URL: community.torproject.org
  STAGING_URL: community.staging.torproject.net
  TRANSLATION_BRANCH: communitytpo-contentspot

include:
  - project: tpo/tpa/ci-templates
    file:
      - lektor.yml
      - static-shim-deploy.yml

# retrieve latest tpo/community/policies build artifact
# and place files under public/policies such that they
# are deployed to community.tpo/policies
.lektor:
  scripts:
    post-build:
      - mkdir public/policies
      - wget -q https://gitlab.torproject.org/api/v4/projects/1972/jobs/artifacts/main/download\?job\=build -O policies.zip
      - unzip policies.zip -d public/policies
      - mv public/policies/public/* public/policies
      - rmdir public/policies/public
